#!/usr/bin/env bash
mkdir Annoy
touch Annoy/index.md
touch Annoy/chapter01.md
touch Annoy/chapter02.md
touch Annoy/chapter03.md
touch Annoy/chapter04.md
touch Annoy/chapter05.md
touch Annoy/chapter06.md
touch Annoy/chapter07.md
touch Annoy/chapter08.md
touch Annoy/chapter09.md
touch Annoy/chapter10.md
touch Annoy/chapter11.md
touch Annoy/chapter12.md
touch Annoy/chapter13.md
touch Annoy/chapter14.md
touch Annoy/chapter15.md
touch Annoy/chapter16.md
touch Annoy/chapter17.md
touch Annoy/chapter18.md
touch Annoy/chapter19.md
touch Annoy/chapter20.md
touch Annoy/chapter21.md
touch Annoy/chapter22.md
touch Annoy/chapter23.md
touch Annoy/chapter24.md
touch Annoy/chapter25.md

mkdir Chronicles
touch Chronicles/index.md
touch Chronicles/chapter01.md
touch Chronicles/chapter02.md
touch Chronicles/chapter03.md
touch Chronicles/chapter04.md
touch Chronicles/chapter05.md
touch Chronicles/chapter06.md
touch Chronicles/chapter07.md
touch Chronicles/chapter08.md
touch Chronicles/chapter09.md
touch Chronicles/chapter10.md
touch Chronicles/chapter11.md
touch Chronicles/chapter12.md
touch Chronicles/chapter13.md
touch Chronicles/chapter14.md
touch Chronicles/chapter15.md
touch Chronicles/chapter16.md
touch Chronicles/chapter17.md
touch Chronicles/chapter18.md
touch Chronicles/chapter19.md
touch Chronicles/chapter20.md
touch Chronicles/chapter21.md
touch Chronicles/chapter22.md
touch Chronicles/chapter24.md
touch Chronicles/chapter25.md
touch Chronicles/chapter26.md
touch Chronicles/chapter27.md
touch Chronicles/chapter28.md
touch Chronicles/chapter29.md
touch Chronicles/chapter30.md
touch Chronicles/chapter31.md
touch Chronicles/chapter32.md
touch Chronicles/chapter33.md
touch Chronicles/chapter34.md
touch Chronicles/chapter35.md
touch Chronicles/chapter36.md
touch Chronicles/chapter37.md
touch Chronicles/chapter38.md
touch Chronicles/chapter39.md

mkdir Justice
touch Justice/index.md
touch Justice/chapter01.md
touch Justice/chapter02.md
touch Justice/chapter03.md
touch Justice/chapter04.md
touch Justice/chapter05.md
touch Justice/chapter06.md
touch Justice/chapter07.md
touch Justice/chapter08.md
touch Justice/chapter09.md

mkdir Proclamations
touch Proclamations/index.md
touch Proclamations/chapter01.md
touch Proclamations/chapter02.md

mkdir Propaganda
touch Propaganda/index.md
touch Propaganda/chapter01.md
touch Propaganda/chapter02.md
touch Propaganda/chapter03.md

mkdir Vengeance
touch Vengeance/index.md
touch Vengeance/chapter01.md
touch Vengeance/chapter02.md
touch Vengeance/chapter03.md
touch Vengeance/chapter04.md
touch Vengeance/chapter05.md
touch Vengeance/chapter06.md

mkdir Victory
touch Victory/index.md
touch Victory/chapter01.md
touch Victory/chapter02.md
touch Victory/chapter03.md

mkdir Villainy
touch Villainy/index.md
touch Villainy/chapter01.md
touch Villainy/chapter02.md
touch Villainy/chapter03.md
touch Villainy/chapter04.md
touch Villainy/chapter05.md
touch Villainy/chapter06.md
touch Villainy/chapter07.md
touch Villainy/chapter08.md
touch Villainy/chapter09.md
touch Villainy/chapter10.md
touch Villainy/chapter11.md
touch Villainy/chapter12.md
touch Villainy/chapter13.md
touch Villainy/chapter14.md
touch Villainy/chapter15.md

mkdir Wrath
touch Wrath/index.md
touch Wrath/chapter01.md
touch Wrath/chapter02.md
touch Wrath/chapter03.md
touch Wrath/chapter04.md

mkdir Apocalypse
touch Apocalypse/index.md
touch Apocalypse/chapter01.md
touch Apocalypse/chapter02.md
touch Apocalypse/chapter03.md
touch Apocalypse/chapter04.md
touch Apocalypse/chapter05.md
